-- Enums required for the authority system.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'site_target') then
    create type public.site_target as enum (
      'cruisesfromgalveston',
      'texascruiseport',
      'houstoncruisetips',
      'houstoncruiseshuttle'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'draft_format') then
    create type public.draft_format as enum ('markdown', 'html');
  end if;

  if not exists (select 1 from pg_type where typname = 'draft_status') then
    create type public.draft_status as enum ('drafted', 'approved', 'rejected', 'revision_requested');
  end if;
end $$;

-- Core authority tables.
create table if not exists public.brand_entities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  domain text,
  entity_type text not null,
  is_yours boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.authority_topics (
  id uuid primary key default gen_random_uuid(),
  topic text not null,
  topic_type text,
  intent text,
  created_at timestamptz default now()
);

create table if not exists public.brand_confusion_signals (
  id uuid primary key default gen_random_uuid(),
  entity_id uuid references public.brand_entities(id),
  signal text,
  source text,
  created_at timestamptz default now()
);

create table if not exists public.content_guardrails (
  id uuid primary key default gen_random_uuid(),
  rule text not null,
  applies_to text,
  active boolean default true,
  created_at timestamptz default now()
);

-- Drafts generated by the publisher agent.
create table if not exists public.content_drafts (
  id uuid primary key default gen_random_uuid(),
  task_id uuid references public.agent_tasks(id),
  site_target public.site_target not null,
  draft_type text not null,
  format public.draft_format not null,
  draft_title text,
  draft_body text,
  authority_role text not null check (authority_role in ('explainer', 'guide', 'context', 'comparison', 'pr')),
  status public.draft_status default 'drafted',
  routing text,
  source_ref text,
  created_by text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (task_id, site_target, format, draft_type)
);

-- RLS: authenticated can read, writes are service-role only.
alter table public.content_drafts enable row level security;

drop policy if exists "authenticated_read" on public.content_drafts;
create policy "authenticated_read"
on public.content_drafts
for select
to authenticated
using (true);

-- Views for dashboards.
create or replace view public.v_ready_drafts as
select
  at.id as task_id,
  kt.topic,
  kt.scope,
  coalesce(at.target_site, 'cruisesfromgalveston') as site_target,
  coalesce(at.source_signal, 'manual') as source_signal,
  kt.priority,
  at.created_at as draft_created_at,
  'drafted'::public.draft_status as status
from public.agent_tasks at
left join public.knowledge_topics kt on kt.id = at.reference_id
where at.ready_for_content = true
order by kt.priority asc nulls last, at.created_at asc;

create or replace view public.v_draft_viewer as
select
  cd.id as draft_id,
  cd.draft_title,
  cd.draft_body,
  cd.site_target,
  cd.draft_type,
  cd.format,
  cd.authority_role,
  cd.status,
  cd.routing,
  cd.source_ref,
  cd.created_at as draft_created_at,
  cd.updated_at as draft_updated_at,
  at.notes as outline,
  at.id as task_id,
  at.reference_id as topic_id,
  kt.topic,
  kt.scope,
  kt.priority
from public.content_drafts cd
left join public.agent_tasks at on at.id = cd.task_id
left join public.knowledge_topics kt on kt.id = at.reference_id;
